version: 2
jobs:
  build:

    working_directory: ~/blockchain-sandbox

    docker:
      - image: maven:3.6.0-jdk-8-alpine
    steps:

      - checkout

      - restore_cache:
          key: blockchain-sandbox-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: blockchain-sandbox-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/kotlinchain-0.0.1-SNAPSHOT.jar